greeting_1 = Message.create(greeting: "Salam there")
greeting_2 = Message.create(greeting: "Hikya vun")
greeting_3 = Message.create(greeting: "Hi there, how are you?")
greeting_4 = Message.create(greeting: "I am a developer")
greeting_5 = Message.create(greeting: "My name is Elmar")
